"""Aggregate API v1 routers."""

from __future__ import annotations

from fastapi import APIRouter

from app.api.v1.routes import (
    account_settings,
    admin_directory,
    admin_employer_verifications,
    admin_overview,
    admin_review,
    admin_review_workflow,
    admin_session,
    admin_verification,
    auth,
    certifications,
    credential_verification,
    dashboard,
    documents,
    educations,
    employment_documents,
    employments,
    freelance_contracts,
    gig_platforms,
    health,
    institution_people,
    institution_workspace,
    internships,
    notifications,
    onboarding,
    organization_people,
    organizations,
    passport,
    passport_shares,
    portfolio,
    projects,
    public_credential_verification,
    public_employer_portal,
    public_employer_verification,
    public_passport,
    public_profile,
    public_vault,
    resume_reviews,
    resumes,
    skills,
    trust_invitations,
    trust_registry,
    trust_score,
    user_documents,
    users,
    verification_connectors,
    verification_requests,
    workspace,
)

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(auth.organization_signup_router)
api_router.include_router(account_settings.router)
api_router.include_router(admin_session.router)
api_router.include_router(users.router)
api_router.include_router(resumes.router)
api_router.include_router(resume_reviews.resume_router)
api_router.include_router(resume_reviews.router)
api_router.include_router(dashboard.router)
api_router.include_router(onboarding.router)
api_router.include_router(organizations.router)
api_router.include_router(organization_people.router)
api_router.include_router(institution_people.router)
api_router.include_router(institution_workspace.router)
api_router.include_router(workspace.router)
api_router.include_router(trust_invitations.org_router)
api_router.include_router(verification_requests.org_router)
api_router.include_router(employments.router)
api_router.include_router(public_employer_verification.router)
api_router.include_router(public_employer_portal.router)
api_router.include_router(public_profile.router)
api_router.include_router(public_passport.router)
api_router.include_router(public_vault.router)
api_router.include_router(credential_verification.router)
api_router.include_router(public_credential_verification.router)
api_router.include_router(documents.router)
api_router.include_router(employment_documents.router)
api_router.include_router(admin_review.router)
api_router.include_router(admin_review_workflow.router)
api_router.include_router(admin_employer_verifications.router)
api_router.include_router(admin_directory.router)
api_router.include_router(admin_overview.router)
api_router.include_router(admin_verification.router)
api_router.include_router(notifications.admin_router)
api_router.include_router(notifications.user_router)
api_router.include_router(verification_connectors.admin_router)
api_router.include_router(trust_registry.admin_router)
api_router.include_router(trust_registry.internal_router)
api_router.include_router(user_documents.router)
api_router.include_router(educations.router)
api_router.include_router(freelance_contracts.router)
api_router.include_router(internships.router)
api_router.include_router(gig_platforms.router)
api_router.include_router(passport.router)
api_router.include_router(passport_shares.router)
api_router.include_router(trust_invitations.router)
api_router.include_router(verification_requests.router)
api_router.include_router(portfolio.router)
api_router.include_router(certifications.router)
api_router.include_router(projects.router)
api_router.include_router(skills.router)
api_router.include_router(trust_score.router)
