/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCommunicationsRouteImport } from './routes/admin.communications'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminRegistryRouteImport } from './routes/admin.registry'
import { Route as AdminRiskRouteImport } from './routes/admin.risk'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as AdminCommunicationsIndexRouteImport } from './routes/admin.communications.index'
import { Route as AdminCommunicationsCommunicationIdRouteImport } from './routes/admin.communications.$communicationId'
import { Route as AdminRegistryIndexRouteImport } from './routes/admin.registry.index'
import { Route as AdminRegistryOrganizationIdRouteImport } from './routes/admin.registry.$organizationId'
import { Route as AdminRiskIndexRouteImport } from './routes/admin.risk.index'
import { Route as AdminRiskInvestigationIdRouteImport } from './routes/admin.risk.$investigationId'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminVerificationsIndexRouteImport } from './routes/admin.verifications.index'
import { Route as AdminVerificationsCaseIdRouteImport } from './routes/admin.verifications.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistryRoute = AdminRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRiskRoute = AdminRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationsIndexRoute =
  AdminCommunicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCommunicationsRoute,
  } as any)
const AdminCommunicationsCommunicationIdRoute =
  AdminCommunicationsCommunicationIdRouteImport.update({
    id: '/$communicationId',
    path: '/$communicationId',
    getParentRoute: () => AdminCommunicationsRoute,
  } as any)
const AdminRegistryIndexRoute = AdminRegistryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRegistryRoute,
} as any)
const AdminRegistryOrganizationIdRoute =
  AdminRegistryOrganizationIdRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => AdminRegistryRoute,
  } as any)
const AdminRiskIndexRoute = AdminRiskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRiskRoute,
} as any)
const AdminRiskInvestigationIdRoute =
  AdminRiskInvestigationIdRouteImport.update({
    id: '/$investigationId',
    path: '/$investigationId',
    getParentRoute: () => AdminRiskRoute,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminVerificationsIndexRoute = AdminVerificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminVerificationsRoute,
} as any)
const AdminVerificationsCaseIdRoute =
  AdminVerificationsCaseIdRouteImport.update({
    id: '/$caseId',
    path: '/$caseId',
    getParentRoute: () => AdminVerificationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/communications': typeof AdminCommunicationsRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/registry': typeof AdminRegistryRouteWithChildren
  '/admin/risk': typeof AdminRiskRouteWithChildren
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/verifications': typeof AdminVerificationsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/communications/$communicationId': typeof AdminCommunicationsCommunicationIdRoute
  '/admin/registry/$organizationId': typeof AdminRegistryOrganizationIdRoute
  '/admin/risk/$investigationId': typeof AdminRiskInvestigationIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/verifications/$caseId': typeof AdminVerificationsCaseIdRoute
  '/admin/communications/': typeof AdminCommunicationsIndexRoute
  '/admin/registry/': typeof AdminRegistryIndexRoute
  '/admin/risk/': typeof AdminRiskIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/verifications/': typeof AdminVerificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin': typeof AdminIndexRoute
  '/admin/communications/$communicationId': typeof AdminCommunicationsCommunicationIdRoute
  '/admin/registry/$organizationId': typeof AdminRegistryOrganizationIdRoute
  '/admin/risk/$investigationId': typeof AdminRiskInvestigationIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/verifications/$caseId': typeof AdminVerificationsCaseIdRoute
  '/admin/communications': typeof AdminCommunicationsIndexRoute
  '/admin/registry': typeof AdminRegistryIndexRoute
  '/admin/risk': typeof AdminRiskIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/verifications': typeof AdminVerificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/communications': typeof AdminCommunicationsRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/registry': typeof AdminRegistryRouteWithChildren
  '/admin/risk': typeof AdminRiskRouteWithChildren
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/verifications': typeof AdminVerificationsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/communications/$communicationId': typeof AdminCommunicationsCommunicationIdRoute
  '/admin/registry/$organizationId': typeof AdminRegistryOrganizationIdRoute
  '/admin/risk/$investigationId': typeof AdminRiskInvestigationIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/verifications/$caseId': typeof AdminVerificationsCaseIdRoute
  '/admin/communications/': typeof AdminCommunicationsIndexRoute
  '/admin/registry/': typeof AdminRegistryIndexRoute
  '/admin/risk/': typeof AdminRiskIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/verifications/': typeof AdminVerificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/communications'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/registry'
    | '/admin/risk'
    | '/admin/system'
    | '/admin/users'
    | '/admin/verifications'
    | '/admin/'
    | '/admin/communications/$communicationId'
    | '/admin/registry/$organizationId'
    | '/admin/risk/$investigationId'
    | '/admin/users/$userId'
    | '/admin/verifications/$caseId'
    | '/admin/communications/'
    | '/admin/registry/'
    | '/admin/risk/'
    | '/admin/users/'
    | '/admin/verifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/system'
    | '/admin'
    | '/admin/communications/$communicationId'
    | '/admin/registry/$organizationId'
    | '/admin/risk/$investigationId'
    | '/admin/users/$userId'
    | '/admin/verifications/$caseId'
    | '/admin/communications'
    | '/admin/registry'
    | '/admin/risk'
    | '/admin/users'
    | '/admin/verifications'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/communications'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/registry'
    | '/admin/risk'
    | '/admin/system'
    | '/admin/users'
    | '/admin/verifications'
    | '/admin/'
    | '/admin/communications/$communicationId'
    | '/admin/registry/$organizationId'
    | '/admin/risk/$investigationId'
    | '/admin/users/$userId'
    | '/admin/verifications/$caseId'
    | '/admin/communications/'
    | '/admin/registry/'
    | '/admin/risk/'
    | '/admin/users/'
    | '/admin/verifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registry': {
      id: '/admin/registry'
      path: '/registry'
      fullPath: '/admin/registry'
      preLoaderRoute: typeof AdminRegistryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/risk': {
      id: '/admin/risk'
      path: '/risk'
      fullPath: '/admin/risk'
      preLoaderRoute: typeof AdminRiskRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communications/': {
      id: '/admin/communications/'
      path: '/'
      fullPath: '/admin/communications/'
      preLoaderRoute: typeof AdminCommunicationsIndexRouteImport
      parentRoute: typeof AdminCommunicationsRoute
    }
    '/admin/communications/$communicationId': {
      id: '/admin/communications/$communicationId'
      path: '/$communicationId'
      fullPath: '/admin/communications/$communicationId'
      preLoaderRoute: typeof AdminCommunicationsCommunicationIdRouteImport
      parentRoute: typeof AdminCommunicationsRoute
    }
    '/admin/registry/': {
      id: '/admin/registry/'
      path: '/'
      fullPath: '/admin/registry/'
      preLoaderRoute: typeof AdminRegistryIndexRouteImport
      parentRoute: typeof AdminRegistryRoute
    }
    '/admin/registry/$organizationId': {
      id: '/admin/registry/$organizationId'
      path: '/$organizationId'
      fullPath: '/admin/registry/$organizationId'
      preLoaderRoute: typeof AdminRegistryOrganizationIdRouteImport
      parentRoute: typeof AdminRegistryRoute
    }
    '/admin/risk/': {
      id: '/admin/risk/'
      path: '/'
      fullPath: '/admin/risk/'
      preLoaderRoute: typeof AdminRiskIndexRouteImport
      parentRoute: typeof AdminRiskRoute
    }
    '/admin/risk/$investigationId': {
      id: '/admin/risk/$investigationId'
      path: '/$investigationId'
      fullPath: '/admin/risk/$investigationId'
      preLoaderRoute: typeof AdminRiskInvestigationIdRouteImport
      parentRoute: typeof AdminRiskRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/verifications/': {
      id: '/admin/verifications/'
      path: '/'
      fullPath: '/admin/verifications/'
      preLoaderRoute: typeof AdminVerificationsIndexRouteImport
      parentRoute: typeof AdminVerificationsRoute
    }
    '/admin/verifications/$caseId': {
      id: '/admin/verifications/$caseId'
      path: '/$caseId'
      fullPath: '/admin/verifications/$caseId'
      preLoaderRoute: typeof AdminVerificationsCaseIdRouteImport
      parentRoute: typeof AdminVerificationsRoute
    }
  }
}

interface AdminCommunicationsRouteChildren {
  AdminCommunicationsCommunicationIdRoute: typeof AdminCommunicationsCommunicationIdRoute
  AdminCommunicationsIndexRoute: typeof AdminCommunicationsIndexRoute
}

const AdminCommunicationsRouteChildren: AdminCommunicationsRouteChildren = {
  AdminCommunicationsCommunicationIdRoute:
    AdminCommunicationsCommunicationIdRoute,
  AdminCommunicationsIndexRoute: AdminCommunicationsIndexRoute,
}

const AdminCommunicationsRouteWithChildren =
  AdminCommunicationsRoute._addFileChildren(AdminCommunicationsRouteChildren)

interface AdminRegistryRouteChildren {
  AdminRegistryOrganizationIdRoute: typeof AdminRegistryOrganizationIdRoute
  AdminRegistryIndexRoute: typeof AdminRegistryIndexRoute
}

const AdminRegistryRouteChildren: AdminRegistryRouteChildren = {
  AdminRegistryOrganizationIdRoute: AdminRegistryOrganizationIdRoute,
  AdminRegistryIndexRoute: AdminRegistryIndexRoute,
}

const AdminRegistryRouteWithChildren = AdminRegistryRoute._addFileChildren(
  AdminRegistryRouteChildren,
)

interface AdminRiskRouteChildren {
  AdminRiskInvestigationIdRoute: typeof AdminRiskInvestigationIdRoute
  AdminRiskIndexRoute: typeof AdminRiskIndexRoute
}

const AdminRiskRouteChildren: AdminRiskRouteChildren = {
  AdminRiskInvestigationIdRoute: AdminRiskInvestigationIdRoute,
  AdminRiskIndexRoute: AdminRiskIndexRoute,
}

const AdminRiskRouteWithChildren = AdminRiskRoute._addFileChildren(
  AdminRiskRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminVerificationsRouteChildren {
  AdminVerificationsCaseIdRoute: typeof AdminVerificationsCaseIdRoute
  AdminVerificationsIndexRoute: typeof AdminVerificationsIndexRoute
}

const AdminVerificationsRouteChildren: AdminVerificationsRouteChildren = {
  AdminVerificationsCaseIdRoute: AdminVerificationsCaseIdRoute,
  AdminVerificationsIndexRoute: AdminVerificationsIndexRoute,
}

const AdminVerificationsRouteWithChildren =
  AdminVerificationsRoute._addFileChildren(AdminVerificationsRouteChildren)

interface AdminRouteChildren {
  AdminCommunicationsRoute: typeof AdminCommunicationsRouteWithChildren
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRegistryRoute: typeof AdminRegistryRouteWithChildren
  AdminRiskRoute: typeof AdminRiskRouteWithChildren
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminVerificationsRoute: typeof AdminVerificationsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommunicationsRoute: AdminCommunicationsRouteWithChildren,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRegistryRoute: AdminRegistryRouteWithChildren,
  AdminRiskRoute: AdminRiskRouteWithChildren,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminVerificationsRoute: AdminVerificationsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
