/**
 * Admin Portal — Verification case types and deterministic mock cases.
 *
 * Keep this file free of UI imports. Replace the constant exports with
 * TanStack Query hooks (e.g. useVerificationCases({ filters })) once the
 * real admin verification API is available.
 */

import type { Priority, VerificationStatus } from "./types";

export type VerificationType =
  "employment" | "education" | "certification" | "identity" | "platform" | "reference";

export type OrganizationStatus = "resolved" | "suggested_match" | "unresolved" | "duplicate_review";

export type SlaState = "within" | "approaching" | "breached";

export type OutreachStatus = "not_started" | "sent" | "bounced" | "responded";

export type AttentionFlag =
  | "document_mismatch"
  | "missing_evidence"
  | "contact_unverified"
  | "possible_duplicate"
  | "email_bounced"
  | "previous_correction"
  | "risk_review_required";

/**
 * Fictional operational assignees. Role-based labels are preferred so
 * mock rosters don't leak into real UX later.
 */
export type Assignee = "Aman Jha" | "Operations Reviewer" | "Trust & Safety" | "Unassigned";

export const ALL_ASSIGNEES: Assignee[] = [
  "Aman Jha",
  "Operations Reviewer",
  "Trust & Safety",
  "Unassigned",
];

export interface VerificationCase {
  id: string;
  reference: string;
  candidateId: string;
  candidateName: string;
  candidateEmail: string;
  candidateAvatarInitials: string;
  organizationId: string;
  organizationName: string;
  roleOrProgram: string;
  verificationType: VerificationType;
  status: VerificationStatus;
  priority: Priority;
  /** ISO timestamp. */
  submittedAt: string;
  /** ISO timestamp. */
  updatedAt: string;
  assignedReviewer: Assignee;
  evidenceCount: number;
  organizationStatus: OrganizationStatus;
  slaState: SlaState;
  attentionFlags: AttentionFlag[];
  outreachStatus: OutreachStatus;
  correctionCount: number;
  lastActivitySummary: string;
}

// All mock times are computed from a single reference frozen at module
// load, so records don't shift between renders within the same session.
const NOW = new Date(Math.floor(Date.now() / 3_600_000) * 3_600_000);

function daysAgo(days: number, hours = 0): string {
  const d = new Date(NOW);
  d.setUTCHours(d.getUTCHours() - hours);
  d.setUTCDate(d.getUTCDate() - days);
  return d.toISOString();
}

// ---------- Type labels (used by UI) ----------
export const VERIFICATION_TYPE_LABEL: Record<VerificationType, string> = {
  employment: "Employment",
  education: "Education",
  certification: "Certification",
  identity: "Identity",
  platform: "Platform",
  reference: "Reference",
};

export const ORGANIZATION_STATUS_LABEL: Record<OrganizationStatus, string> = {
  resolved: "Resolved",
  suggested_match: "Suggested match",
  unresolved: "Unresolved",
  duplicate_review: "Duplicate review",
};

export const SLA_LABEL: Record<SlaState, string> = {
  within: "Within SLA",
  approaching: "Approaching SLA",
  breached: "Breached SLA",
};

export const ATTENTION_FLAG_LABEL: Record<AttentionFlag, string> = {
  document_mismatch: "Document mismatch",
  missing_evidence: "Missing evidence",
  contact_unverified: "Contact unverified",
  possible_duplicate: "Possible duplicate",
  email_bounced: "Email bounced",
  previous_correction: "Previous correction",
  risk_review_required: "Risk review required",
};

export const COMPLETED_STATUSES: VerificationStatus[] = [
  "verified",
  "rejected",
  "unable_to_verify",
];

// ---------- Deterministic mock cases ----------
// Every active sub-queue is represented, along with completed cases,
// urgent + normal priorities, unassigned rows, SLA-breached rows,
// unresolved organizations, multi-flag cases and outreach activity.
export const mockVerificationCases: VerificationCase[] = [
  {
    id: "vc-001",
    reference: "KVR-24081",
    candidateId: "cand-101",
    candidateName: "Jonas Weiss",
    candidateEmail: "jonas.weiss@example.com",
    candidateAvatarInitials: "JW",
    organizationId: "org-11",
    organizationName: "Northwind Analytics",
    roleOrProgram: "Senior Data Engineer",
    verificationType: "employment",
    status: "pending_review",
    priority: "urgent",
    submittedAt: daysAgo(2, 4),
    updatedAt: daysAgo(0, 3),
    assignedReviewer: "Aman Jha",
    evidenceCount: 4,
    organizationStatus: "resolved",
    slaState: "breached",
    attentionFlags: ["document_mismatch", "previous_correction"],
    outreachStatus: "sent",
    correctionCount: 1,
    lastActivitySummary: "Outreach sent to hr@northwind.example",
  },
  {
    id: "vc-002",
    reference: "KVR-24082",
    candidateId: "cand-102",
    candidateName: "Priya Shah",
    candidateEmail: "priya.shah@example.com",
    candidateAvatarInitials: "PS",
    organizationId: "org-12",
    organizationName: "Globex Ltd",
    roleOrProgram: "Product Designer",
    verificationType: "employment",
    status: "resubmitted",
    priority: "high",
    submittedAt: daysAgo(1, 6),
    updatedAt: daysAgo(0, 1),
    assignedReviewer: "Aman Jha",
    evidenceCount: 6,
    organizationStatus: "resolved",
    slaState: "approaching",
    attentionFlags: ["previous_correction"],
    outreachStatus: "not_started",
    correctionCount: 1,
    lastActivitySummary: "Candidate resubmitted corrections",
  },
  {
    id: "vc-003",
    reference: "KVR-24083",
    candidateId: "cand-103",
    candidateName: "Marco Bianchi",
    candidateEmail: "marco.bianchi@example.com",
    candidateAvatarInitials: "MB",
    organizationId: "org-13",
    organizationName: "Acme Corp",
    roleOrProgram: "Engineering Manager",
    verificationType: "employment",
    status: "awaiting_employer",
    priority: "normal",
    submittedAt: daysAgo(4, 0),
    updatedAt: daysAgo(1, 0),
    assignedReviewer: "Operations Reviewer",
    evidenceCount: 3,
    organizationStatus: "resolved",
    slaState: "within",
    attentionFlags: [],
    outreachStatus: "sent",
    correctionCount: 0,
    lastActivitySummary: "Awaiting employer confirmation",
  },
  {
    id: "vc-004",
    reference: "KVR-24084",
    candidateId: "cand-104",
    candidateName: "Lena Fischer",
    candidateEmail: "lena.fischer@example.com",
    candidateAvatarInitials: "LF",
    organizationId: "org-14",
    organizationName: "Umbrella GmbH",
    roleOrProgram: "Compliance Analyst",
    verificationType: "employment",
    status: "corrections_requested",
    priority: "high",
    submittedAt: daysAgo(3, 2),
    updatedAt: daysAgo(0, 5),
    assignedReviewer: "Aman Jha",
    evidenceCount: 2,
    organizationStatus: "suggested_match",
    slaState: "approaching",
    attentionFlags: ["missing_evidence"],
    outreachStatus: "not_started",
    correctionCount: 1,
    lastActivitySummary: "Correction requested: employment dates",
  },
  {
    id: "vc-005",
    reference: "KVR-24085",
    candidateId: "cand-105",
    candidateName: "Ravi Patel",
    candidateEmail: "ravi.patel@example.com",
    candidateAvatarInitials: "RP",
    organizationId: "org-15",
    organizationName: "Initech LLC",
    roleOrProgram: "Backend Engineer",
    verificationType: "employment",
    status: "awaiting_organization",
    priority: "normal",
    submittedAt: daysAgo(2, 0),
    updatedAt: daysAgo(1, 4),
    assignedReviewer: "Unassigned",
    evidenceCount: 3,
    organizationStatus: "unresolved",
    slaState: "within",
    attentionFlags: ["possible_duplicate"],
    outreachStatus: "not_started",
    correctionCount: 0,
    lastActivitySummary: "Organization could not be matched",
  },
  {
    id: "vc-006",
    reference: "KVR-24086",
    candidateId: "cand-106",
    candidateName: "Sofia Martins",
    candidateEmail: "sofia.martins@example.com",
    candidateAvatarInitials: "SM",
    organizationId: "org-16",
    organizationName: "Wayne Industries",
    roleOrProgram: "MBA — Class of 2019",
    verificationType: "education",
    status: "pending_review",
    priority: "high",
    submittedAt: daysAgo(1, 20),
    updatedAt: daysAgo(0, 2),
    assignedReviewer: "Unassigned",
    evidenceCount: 5,
    organizationStatus: "resolved",
    slaState: "approaching",
    attentionFlags: ["document_mismatch"],
    outreachStatus: "not_started",
    correctionCount: 0,
    lastActivitySummary: "Awaiting reviewer assignment",
  },
  {
    id: "vc-007",
    reference: "KVR-24087",
    candidateId: "cand-107",
    candidateName: "Daniel Kim",
    candidateEmail: "daniel.kim@example.com",
    candidateAvatarInitials: "DK",
    organizationId: "org-17",
    organizationName: "AWS Certified Programs",
    roleOrProgram: "AWS Solutions Architect — Professional",
    verificationType: "certification",
    status: "verified",
    priority: "normal",
    submittedAt: daysAgo(9, 0),
    updatedAt: daysAgo(1, 0),
    assignedReviewer: "Operations Reviewer",
    evidenceCount: 2,
    organizationStatus: "resolved",
    slaState: "within",
    attentionFlags: [],
    outreachStatus: "responded",
    correctionCount: 0,
    lastActivitySummary: "Verification completed",
  },
  {
    id: "vc-008",
    reference: "KVR-24088",
    candidateId: "cand-108",
    candidateName: "Ines Duarte",
    candidateEmail: "ines.duarte@example.com",
    candidateAvatarInitials: "ID",
    organizationId: "org-18",
    organizationName: "Stark Industries",
    roleOrProgram: "Senior Product Manager",
    verificationType: "employment",
    status: "failed_outreach",
    priority: "urgent",
    submittedAt: daysAgo(6, 0),
    updatedAt: daysAgo(0, 8),
    assignedReviewer: "Trust & Safety",
    evidenceCount: 3,
    organizationStatus: "resolved",
    slaState: "breached",
    attentionFlags: ["email_bounced", "contact_unverified"],
    outreachStatus: "bounced",
    correctionCount: 0,
    lastActivitySummary: "Outreach bounced from hr@stark.example",
  },
  {
    id: "vc-009",
    reference: "KVR-24089",
    candidateId: "cand-109",
    candidateName: "Hiroshi Tanaka",
    candidateEmail: "hiroshi.tanaka@example.com",
    candidateAvatarInitials: "HT",
    organizationId: "org-19",
    organizationName: "Cyberdyne Systems",
    roleOrProgram: "Robotics Engineer",
    verificationType: "employment",
    status: "clarification_requested",
    priority: "normal",
    submittedAt: daysAgo(3, 6),
    updatedAt: daysAgo(0, 12),
    assignedReviewer: "Aman Jha",
    evidenceCount: 4,
    organizationStatus: "resolved",
    slaState: "within",
    attentionFlags: [],
    outreachStatus: "sent",
    correctionCount: 0,
    lastActivitySummary: "Clarification requested on role dates",
  },
  {
    id: "vc-010",
    reference: "KVR-24090",
    candidateId: "cand-110",
    candidateName: "Emily Carter",
    candidateEmail: "emily.carter@example.com",
    candidateAvatarInitials: "EC",
    organizationId: "org-20",
    organizationName: "Hooli Inc",
    roleOrProgram: "Staff Engineer",
    verificationType: "employment",
    status: "rejected",
    priority: "normal",
    submittedAt: daysAgo(12, 0),
    updatedAt: daysAgo(3, 0),
    assignedReviewer: "Operations Reviewer",
    evidenceCount: 2,
    organizationStatus: "resolved",
    slaState: "within",
    attentionFlags: ["risk_review_required"],
    outreachStatus: "responded",
    correctionCount: 0,
    lastActivitySummary: "Rejected after risk review",
  },
  {
    id: "vc-011",
    reference: "KVR-24091",
    candidateId: "cand-111",
    candidateName: "Aisha Bello",
    candidateEmail: "aisha.bello@example.com",
    candidateAvatarInitials: "AB",
    organizationId: "org-21",
    organizationName: "Massive Dynamic",
    roleOrProgram: "Full-Stack Developer",
    verificationType: "employment",
    status: "pending_review",
    priority: "normal",
    submittedAt: daysAgo(0, 14),
    updatedAt: daysAgo(0, 14),
    assignedReviewer: "Unassigned",
    evidenceCount: 3,
    organizationStatus: "resolved",
    slaState: "within",
    attentionFlags: [],
    outreachStatus: "not_started",
    correctionCount: 0,
    lastActivitySummary: "Submitted for review",
  },
  {
    id: "vc-012",
    reference: "KVR-24092",
    candidateId: "cand-112",
    candidateName: "Noah Bergström",
    candidateEmail: "noah.bergstrom@example.com",
    candidateAvatarInitials: "NB",
    organizationId: "org-22",
    organizationName: "Soylent Corp",
    roleOrProgram: "Head of Growth",
    verificationType: "reference",
    status: "awaiting_employer",
    priority: "low",
    submittedAt: daysAgo(5, 3),
    updatedAt: daysAgo(2, 0),
    assignedReviewer: "Operations Reviewer",
    evidenceCount: 1,
    organizationStatus: "resolved",
    slaState: "within",
    attentionFlags: [],
    outreachStatus: "sent",
    correctionCount: 0,
    lastActivitySummary: "Reference contacted",
  },
  {
    id: "vc-013",
    reference: "KVR-24093",
    candidateId: "cand-113",
    candidateName: "Yara Haddad",
    candidateEmail: "yara.haddad@example.com",
    candidateAvatarInitials: "YH",
    organizationId: "org-23",
    organizationName: "Pied Piper",
    roleOrProgram: "Compression Engineer",
    verificationType: "employment",
    status: "resubmitted",
    priority: "normal",
    submittedAt: daysAgo(4, 4),
    updatedAt: daysAgo(0, 6),
    assignedReviewer: "Aman Jha",
    evidenceCount: 5,
    organizationStatus: "resolved",
    slaState: "within",
    attentionFlags: ["previous_correction"],
    outreachStatus: "sent",
    correctionCount: 1,
    lastActivitySummary: "Resubmitted after clarification",
  },
  {
    id: "vc-014",
    reference: "KVR-24094",
    candidateId: "cand-114",
    candidateName: "Kwame Mensah",
    candidateEmail: "kwame.mensah@example.com",
    candidateAvatarInitials: "KM",
    organizationId: "org-24",
    organizationName: "Vandelay Industries",
    roleOrProgram: "Regional Director",
    verificationType: "employment",
    status: "awaiting_organization",
    priority: "high",
    submittedAt: daysAgo(2, 12),
    updatedAt: daysAgo(1, 3),
    assignedReviewer: "Trust & Safety",
    evidenceCount: 4,
    organizationStatus: "duplicate_review",
    slaState: "approaching",
    attentionFlags: ["possible_duplicate", "risk_review_required"],
    outreachStatus: "not_started",
    correctionCount: 0,
    lastActivitySummary: "Two possible org matches identified",
  },
  {
    id: "vc-015",
    reference: "KVR-24095",
    candidateId: "cand-115",
    candidateName: "Chen Wei",
    candidateEmail: "chen.wei@example.com",
    candidateAvatarInitials: "CW",
    organizationId: "org-25",
    organizationName: "Kairo Verified ID",
    roleOrProgram: "Government ID document",
    verificationType: "identity",
    status: "verified",
    priority: "normal",
    submittedAt: daysAgo(2, 0),
    updatedAt: daysAgo(1, 12),
    assignedReviewer: "Aman Jha",
    evidenceCount: 2,
    organizationStatus: "resolved",
    slaState: "within",
    attentionFlags: [],
    outreachStatus: "responded",
    correctionCount: 0,
    lastActivitySummary: "Identity verified",
  },
  {
    id: "vc-016",
    reference: "KVR-24096",
    candidateId: "cand-116",
    candidateName: "Owen Reilly",
    candidateEmail: "owen.reilly@example.com",
    candidateAvatarInitials: "OR",
    organizationId: "org-26",
    organizationName: "GitHub Contributions",
    roleOrProgram: "Open-source maintainer",
    verificationType: "platform",
    status: "pending_review",
    priority: "low",
    submittedAt: daysAgo(0, 22),
    updatedAt: daysAgo(0, 22),
    assignedReviewer: "Operations Reviewer",
    evidenceCount: 2,
    organizationStatus: "resolved",
    slaState: "within",
    attentionFlags: [],
    outreachStatus: "not_started",
    correctionCount: 0,
    lastActivitySummary: "Awaiting review",
  },
  {
    id: "vc-017",
    reference: "KVR-24097",
    candidateId: "cand-117",
    candidateName: "Fatima Zahra",
    candidateEmail: "fatima.zahra@example.com",
    candidateAvatarInitials: "FZ",
    organizationId: "org-27",
    organizationName: "Weyland-Yutani",
    roleOrProgram: "Bio-engineer",
    verificationType: "employment",
    status: "unable_to_verify",
    priority: "normal",
    submittedAt: daysAgo(20, 0),
    updatedAt: daysAgo(7, 0),
    assignedReviewer: "Trust & Safety",
    evidenceCount: 1,
    organizationStatus: "unresolved",
    slaState: "within",
    attentionFlags: ["contact_unverified"],
    outreachStatus: "bounced",
    correctionCount: 1,
    lastActivitySummary: "Employer contact could not be verified",
  },
  {
    id: "vc-018",
    reference: "KVR-24098",
    candidateId: "cand-118",
    candidateName: "Andrés Rojas",
    candidateEmail: "andres.rojas@example.com",
    candidateAvatarInitials: "AR",
    organizationId: "org-28",
    organizationName: "Tyrell Corporation",
    roleOrProgram: "Site Reliability Engineer",
    verificationType: "employment",
    status: "corrections_requested",
    priority: "urgent",
    submittedAt: daysAgo(5, 0),
    updatedAt: daysAgo(0, 2),
    assignedReviewer: "Aman Jha",
    evidenceCount: 3,
    organizationStatus: "resolved",
    slaState: "breached",
    attentionFlags: ["missing_evidence", "document_mismatch", "previous_correction"],
    outreachStatus: "not_started",
    correctionCount: 2,
    lastActivitySummary: "Second correction requested",
  },
  {
    id: "vc-019",
    reference: "KVR-24099",
    candidateId: "cand-119",
    candidateName: "Mira Novak",
    candidateEmail: "mira.novak@example.com",
    candidateAvatarInitials: "MN",
    organizationId: "org-29",
    organizationName: "Aperture Science",
    roleOrProgram: "Research Scientist",
    verificationType: "education",
    status: "clarification_requested",
    priority: "high",
    submittedAt: daysAgo(2, 8),
    updatedAt: daysAgo(0, 4),
    assignedReviewer: "Unassigned",
    evidenceCount: 2,
    organizationStatus: "suggested_match",
    slaState: "approaching",
    attentionFlags: ["document_mismatch"],
    outreachStatus: "not_started",
    correctionCount: 0,
    lastActivitySummary: "Awaiting candidate clarification",
  },
  {
    id: "vc-020",
    reference: "KVR-24100",
    candidateId: "cand-120",
    candidateName: "Julia Kowalski",
    candidateEmail: "julia.kowalski@example.com",
    candidateAvatarInitials: "JK",
    organizationId: "org-30",
    organizationName: "Oscorp Industries",
    roleOrProgram: "VP Engineering",
    verificationType: "employment",
    status: "failed_outreach",
    priority: "high",
    submittedAt: daysAgo(7, 0),
    updatedAt: daysAgo(0, 5),
    assignedReviewer: "Trust & Safety",
    evidenceCount: 3,
    organizationStatus: "resolved",
    slaState: "breached",
    attentionFlags: ["email_bounced"],
    outreachStatus: "bounced",
    correctionCount: 0,
    lastActivitySummary: "Third outreach attempt bounced",
  },
  {
    id: "vc-021",
    reference: "KVR-24101",
    candidateId: "cand-121",
    candidateName: "Tomás Silva",
    candidateEmail: "tomas.silva@example.com",
    candidateAvatarInitials: "TS",
    organizationId: "org-31",
    organizationName: "InGen Corporation",
    roleOrProgram: "Field Researcher",
    verificationType: "reference",
    status: "pending_review",
    priority: "normal",
    submittedAt: daysAgo(1, 2),
    updatedAt: daysAgo(0, 6),
    assignedReviewer: "Operations Reviewer",
    evidenceCount: 2,
    organizationStatus: "resolved",
    slaState: "within",
    attentionFlags: [],
    outreachStatus: "sent",
    correctionCount: 0,
    lastActivitySummary: "Reference response pending",
  },
  {
    id: "vc-022",
    reference: "KVR-24102",
    candidateId: "cand-122",
    candidateName: "Elif Demir",
    candidateEmail: "elif.demir@example.com",
    candidateAvatarInitials: "ED",
    organizationId: "org-32",
    organizationName: "Nakatomi Trading",
    roleOrProgram: "Financial Analyst",
    verificationType: "employment",
    status: "awaiting_employer",
    priority: "high",
    submittedAt: daysAgo(6, 12),
    updatedAt: daysAgo(0, 10),
    assignedReviewer: "Aman Jha",
    evidenceCount: 4,
    organizationStatus: "resolved",
    slaState: "approaching",
    attentionFlags: [],
    outreachStatus: "sent",
    correctionCount: 0,
    lastActivitySummary: "Awaiting employer response — day 6",
  },
  {
    id: "vc-023",
    reference: "KVR-24103",
    candidateId: "cand-123",
    candidateName: "Bruno Costa",
    candidateEmail: "bruno.costa@example.com",
    candidateAvatarInitials: "BC",
    organizationId: "org-33",
    organizationName: "LexCorp",
    roleOrProgram: "Legal Counsel",
    verificationType: "employment",
    status: "verified",
    priority: "normal",
    submittedAt: daysAgo(14, 0),
    updatedAt: daysAgo(2, 0),
    assignedReviewer: "Operations Reviewer",
    evidenceCount: 3,
    organizationStatus: "resolved",
    slaState: "within",
    attentionFlags: [],
    outreachStatus: "responded",
    correctionCount: 0,
    lastActivitySummary: "Verification completed",
  },
  {
    id: "vc-024",
    reference: "KVR-24104",
    candidateId: "cand-124",
    candidateName: "Nadia Popov",
    candidateEmail: "nadia.popov@example.com",
    candidateAvatarInitials: "NP",
    organizationId: "org-34",
    organizationName: "Blue Sun",
    roleOrProgram: "Head of Research",
    verificationType: "employment",
    status: "resubmitted",
    priority: "urgent",
    submittedAt: daysAgo(4, 0),
    updatedAt: daysAgo(0, 0),
    assignedReviewer: "Unassigned",
    evidenceCount: 6,
    organizationStatus: "resolved",
    slaState: "breached",
    attentionFlags: ["previous_correction", "risk_review_required"],
    outreachStatus: "sent",
    correctionCount: 2,
    lastActivitySummary: "Resubmitted just now",
  },
];
